<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Create New Lead_ifrm-ta</name>
   <tag></tag>
   <elementGuidId>f53735fe-f908-4251-8b88-244acd659b6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Create New Lead'])[1]/following::iframe[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>left</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>all-frames</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ifrm-tag</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>420px</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>yes</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://isvqa2.academicpartnerships.com/NewLead/home?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IlNoaXZhbmFuZGEgTVMiLCJnaXZlbl9uYW1lIjoiU2hpdmFuYW5kYSIsInJvbGUiOiJTeXN0ZW0gQWRtaW5pc3RyYXRvciIsImNlcnRzZXJpYWxudW1iZXIiOiJiMTM4OTA3ZS02NTU2LWU3MTEtODBjZC0wMDBkM2E5MWQzZjUiLCJ1cG4iOiJCRVNUXFxTaGl2YW5hbmRhLk1TIiwiVVNFUl9BVURJVCI6ImZhbHNlIiwiUlVMRVNfRU5HSU5FIjpbIkNSRUFURSIsIlVQREFURSIsIkRFTEVURSJdLCJOQVRJVkVfQ1JNIjoiT1BQT1JUVU5JVFkiLCJuYmYiOjE1NDkzOTU0MDYsImV4cCI6MTU0OTQ0OTQwNiwiaWF0IjoxNTQ5Mzk1NDA2fQ.5NPsrAeIgj6xPLpSlmHCxiD6T6L9RL-2SgpmsIWsOWA</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;uad-content modal-open&quot;]/dialog-holder[1]/dialog-wrapper[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;modal fade show in&quot;]/add-opportunity[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;modal-dialog lead-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body lead-body&quot;]/iframe[@class=&quot;ifrm-tag&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create New Lead'])[1]/following::iframe[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::iframe[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//iframe</value>
   </webElementXpaths>
</WebElementEntity>
