<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Agent Name_TextField</name>
   <tag></tag>
   <elementGuidId>7ed01437-674b-4716-868b-b4f18cefb804</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;uad-content&quot;]/uad-root[1]/div[@class=&quot;container-fluid nopadding&quot;]/div[@class=&quot;wrapper-content&quot;]/div[@class=&quot;col-xs-10 col-sm-10 col-md-10 col-lg-10 content-wrapper nopadding&quot;]/div[@class=&quot;middle-wrapper&quot;]/uad-opportunitydetails[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;opp-details-wrap&quot;]/uad-activitylist[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;activitywrapper&quot;]/div[@class=&quot;customtable&quot;]/uad-phoneactivity[@class=&quot;ng-star-inserted&quot;]/form[@class=&quot;ng-dirty ng-touched ng-invalid&quot;]/div[@class=&quot;phoneactivitywrapper&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row nomargin pad-10&quot;]/div[@class=&quot;row nomargin pt-0 ng-star-inserted&quot;]/div[@class=&quot;flex-inline&quot;]/div[@class=&quot;pos-rel ng-star-inserted&quot;]/div[@class=&quot;agentname&quot;]/ng-select[@class=&quot;searchable ng-single ng-touched ng-dirty ng-invalid&quot;]/div[@class=&quot;ng-control&quot;]/div[@class=&quot;ng-value-container&quot;]/div[@class=&quot;ng-input ng-star-inserted&quot;]/input[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <value>(//input[@type='text'])[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agent Name'])[1]/following::input[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scheduling Activity'])[1]/following::input[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Abdul Muktadeer Mohammed'])[1]/preceding::input[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div[2]/input</value>
   </webElementXpaths>
</WebElementEntity>
